### ISSUE TITLE
Update with latest profiles: 11_3_0_pre5, 11_3_0_pre6, 12_0_0_pre1

### ISSUE THREAD

**Issue by jpata** [jpata/cms-reco-profiling-web#10]
The [profiling job](https://cmssdt.cern.ch/jenkins/job/release-run-reco-profiling/78/console) for [11_3_0_pre6](https://twiki.cern.ch/twiki/bin/viewauth/CMS/RecoTagSetDigest113X#CMSSW_11_3_0_pre6_released_on_15) has completed, the outputs can be found at

```
/eos/cms/store/user/cmsbuild/profiling/data/CMSSW_11_3_0_pre6/slc7_amd64_gcc900/23434.21/
```

@xoqhdgh1002 could you please include this in the next round of updates? We are already aware that CPU igprof results will still be incorrect due to https://github.com/cms-sw/cmssw/issues/33297.

**Comment by jpata** [comment]
@xoqhdgh1002 just a kind ping on this - would you be able to update the html webpage with the pre6 results, using the manual method?

**Comment by jpata** [comment]
The profiles for the following releases have completed:
```
/eos/cms/store/user/cmsbuild/profiling/data/CMSSW_11_3_0_pre5
/eos/cms/store/user/cmsbuild/profiling/data/CMSSW_11_3_0_pre6
/eos/cms/store/user/cmsbuild/profiling/data/CMSSW_12_0_0_pre1
```

The following workflows are available:
- 11834.21 (Run3 workflow)
- 23434.21 (Phase2 workflow)

I also generated the sql3 files from these profile outputs and copied them to `/eos/project/c/cmsweb/www/reco-prof/cgi-bin/data/releases/`.

@xoqhdgh1002 could you please propagate these updates to the HTML web page for next Wednesday? Please also check for copy-paste errors (https://github.com/jpata/cms-reco-profiling-web/issues/9).

**Comment by xoqhdgh1002** [comment]
The webpage is updated!
