### ISSUE TITLE
Improvements to the new javascript-based comp_igprof

### ISSUE THREAD

**Issue by jpata** [jpata/cms-reco-profiling-web#15]
The new javascript-based comp_igprof is very nice! However, we've noticed that under certain resolutions (e.g. 1920 x 1080), the column labels disappear, see attached. 
 
![Screenshot from 2021-06-09 10-19-18](https://user-images.githubusercontent.com/69717/121310578-2c99ce80-c90c-11eb-9d00-d5542033d561.png)

It would also be nice to make the bar chart on a logarithmic y scale, to better see the small differences towards the right side.

cc @xoqhdgh1002

**Comment by xoqhdgh1002** [comment]
Thanks for your comments. I will check the plotly module and fix the column label. I will get back to you as soon as possible!

**Comment by dpiparo** [comment]
Indeed very nice visualisation. Another small issue I have on a big screen with firefox is that if I try to scroll, the names of the symbols get messed up

![image](https://user-images.githubusercontent.com/7850302/121352163-da1cda00-c92c-11eb-9a9a-2ead989cf3eb.png)

**Comment by jpata** [comment]
And here's how it looks like under Safari and a smaller screen (labels are a bit too large, they should scale themselves to be smaller...):
<img width="1150" alt="Screenshot 2021-06-09 at 15 33 55" src="https://user-images.githubusercontent.com/69717/121355029-24f01f00-c938-11eb-8e9a-b300babe15de.png">

**Comment by jpata** [comment]
This has been fixed and looks better now!
![Screenshot from 2021-07-21 20-17-28](https://user-images.githubusercontent.com/69717/126531638-881cede6-a722-4b57-a7e0-1c578ede16fb.png)

(AFAIK, the javascript comparison page is not under git tracking)
