### ISSUE TITLE
propagate cmdlog to the web page

### ISSUE THREAD

**Issue by jpata** [jpata/cms-reco-profiling-web#21]
The profiling command logs
```
/eos/cms/store/user/cmsbuild/profiling/data/CMSSW_12_0_0_pre4/slc7_amd64_gcc900/23434.21/cmdLog_profiling.sh
```

should be copied to in an appropriate webpage subdirectory, for example  
```
/eos/project/c/cmsweb/www/reco-prof/results/cmdlog/CMSSW_12_0_0_pre4/23434.21
```

and the web page index.html could be updated correspondingly for the releases that miss the cmdLog.

**Comment by jpata** [comment]
cc @xoqhdgh1002

**Comment by jpata** [comment]
Note that (as reported by Bongho today) cmdLog is available only from 11_3_0_pre5 and onwards, we didn't save it in the jenkins job prior to that. If needed, they can be added later manually.

**Comment by jpata** [comment]
I realized we never propagated the cmdLog to the web page. For the releases it's available, can this be added?

**Comment by xoqhdgh1002** [comment]
I checked that. 
I'll finish propagation for cmdLog until Saturday.

**Comment by xoqhdgh1002** [comment]
It's done!
Please check the correction and comment!

**Comment by jpata** [comment]
Thanks, it looks correct, it's updated in http://cms-reco-profiling.web.cern.ch.
