### ISSUE TITLE
Tooltip display in the summary page is truncated

### ISSUE THREAD

**Issue by slava77** [jpata/cms-reco-profiling-web#23]
e.g. in http://cms-reco-profiling.web.cern.ch/cms-reco-profiling/results/summary_plot_html/CMSSW_12_0_X_step3.html
the text for CMSSW_12_0_0_pre5 is truncated to `CMSSW_12_0_0...`
<img width="518" alt="image" src="https://user-images.githubusercontent.com/4676718/128351986-9fb7d140-af43-4262-948d-60efa0e5c2c0.png">

one option to resolve this is to drop `CMSSW_` if there is no way to control the width of the tooltip.

**Comment by slava77** [comment]
@xoqhdgh1002

**Comment by jpata** [comment]
this is fixed!
