### ISSUE TITLE
circles pichart links groups field needs an update to `packages`

### ISSUE THREAD

**Issue by slava77** [jpata/cms-reco-profiling-web#34]
I noticed that the piechart/circles links are not displaying correctly. It looks like `groups=package` should be `groups=packages`

e.g. 
http://cms-reco-profiling.web.cern.ch/cms-reco-profiling/circles/piechart.php?local=false&dataset=CMSSW_12_2_0_pre2%2Fslc7_amd64_gcc900%2F34834.21%2Fstep3_circles&resource=time_real&colours=default&groups=packages&threshold=0

while the link in the current page is http://cms-reco-profiling.web.cern.ch/cms-reco-profiling/circles/piechart.php?local=false&dataset=CMSSW_12_2_0_pre2%2Fslc7_amd64_gcc900%2F34834.21%2Fstep3_circles&resource=time_real&colours=default&groups=package&threshold=0
the `group=package` is not recognized and the server side defaults it to `hlt` which is not the most appropriate in this case.

**Comment by slava77** [comment]
@xoqhdgh1002 
please check

**Comment by xoqhdgh1002** [comment]
I modified the part you mentioned and updated the PR.
Thanks for your notice!

**Comment by jpata** [comment]
this is solved in #36
