### ISSUE TITLE
Monitor the max memory of a Run3 production workflow

### ISSUE THREAD

**Issue by jpata** [jpata/cms-reco-profiling-web#35]
In order to be aware how close we are to tripping the memory limits at T0 with the reco workflows, we should monitor the max memory of a production like, multi-threaded Run3 workflow.

Some notes from a discussion with Slava.
- getTimeMemorySummary with 8 threads and a plot like http://cms-reco-profiling.web.cern.ch/cms-reco-profiling/results/summary_plot_html/CMSSW_12_2_step3_11834.21.html could be a good starting point
- monitoring the max memory from the system side is more granular (intra-module peaks): https://github.com/slava77/cms-reco-tools/blob/master/monitorProcStat.sh
- 400 events on 8 threads may be too small to have a good capture of the memory peak. This is a rather stochastic process to get the peak.

**Comment by jpata** [comment]
To test this out, I ran 11834.21 with 8 threads and took a look at the TimeMemoryInfo printouts. I can get a graph like this.
![mem_8core](https://user-images.githubusercontent.com/69717/143548846-adf8bab4-62f4-465c-a3bf-6ec389a5615b.png)
 
A few questions arose:
- is the workflow a reasonable representation of what's run at T0?
- do we care about vsize or rss, or both?

Once we have something reasonable to benchmark, we can put this in the reco profiling jenkins script https://github.com/cms-sw/cms-bot/blob/master/reco_profiling/profileRunner.py
and ask Bongho to propagate these results to the reco profiling web page.

@slava77 @clacaputo

**Comment by slava77** [comment]
> A few questions arose:
> 
>     * is the workflow a reasonable representation of what's run at T0?

not quite.
Prompt also has PAT/miniAOD.

If we were to target something heavier in T0 as a limit, then some DQM,alca and a few skims should be added. Perhaps it's best to start by just adding PAT for the MC-based test. 

It would be easier to build a config for data to have something representative of T0.

> 
>     * do we care about vsize or rss, or both?

just RSS should be good; VSIZE is not informative anymore (is it since 64bit)

**Comment by jpata** [comment]
How about this:
```
runTheMatrix.py --ibeos -l 136.889 --command="-n 5000 --nThreads 8 --customise Validation/Performance/TimeMemoryInfo.py"
```
which gives 136.889_RunMET2018D+RunMET2018D+HLTDR2_2018+RECODR2_2018reHLT_skimMET_Prompt+HARVEST2018_Prompt

**Comment by slava77** [comment]
> > 11834.21_TTbar_14TeV+2021PU_ProdLike+TTbar_14TeV_TuneCP5_GenSim+DigiPU+RecoPU+**MiniAODPU**+NanoPU+Nano
> 
> I may be confused, but doesn't this mean PAT/miniAOD is running? Or is the issue that it's running in a separate step (step4)?

running pieces in  separate jobs reduces the memory needs, no?

**Comment by jpata** [comment]
Sure, that makes sense. I'm simply trying to understand what are the different configurations that are even possible, and how T0 is differing from the usual workflow we are testing.

**Comment by slava77** [comment]
> 

this looks more reasonable to me for a T0-like job

**Comment by jpata** [comment]
On `136.889_RunMET2018D+RunMET2018D+HLTDR2_2018+RECODR2_2018reHLT_skimMET_Prompt+HARVEST2018_Prompt/step3_RAW2DIGI_L1Reco_RECO_SKIM_EI_PAT_ALCA_DQM.py` we can get the following graph for RSS use over 4k events:

![image](https://user-images.githubusercontent.com/69717/143828930-30b0040d-aa60-47d5-a01e-af66a7c690b9.png)

**Comment by jpata** [comment]
And here's the RSS from `monitorProcStat.sh`.
![image](https://user-images.githubusercontent.com/69717/143849317-e42da191-2dec-4e7b-94a2-df7b2815e522.png)
It doesn't look like there's significantly more intra-module memory spikes detected by the `monitorProcStat.sh` than can be seen in the `TimeMemoryInfo`, so perhaps the latter is fine to start with?

**Comment by slava77** [comment]
> It doesn't look like there's significantly more intra-module memory spikes detected by the `monitorProcStat.sh` than can be seen in the `TimeMemoryInfo`, so perhaps the latter is fine to start with?

multithreded mem check effectively samples during the other events still processing. So, it should cover roughly time_per_event/7.

BTW, which value did you pick from monitorProcStat outputs? 
The first column reports the peak and it never goes down.

**Comment by jpata** [comment]
> So, it should cover roughly time_per_event/7.

So TimeMemoryInfo should be fine to start with?

> BTW, which value did you pick from monitorProcStat outputs?

I picked the 7th value, it seemed to correlate mostly with what's measured also by TimeMemoryInfo.

**Comment by slava77** [comment]
I suggest to display the peak from monitorProcStat as well. It does not require a separate rerun of the job.

**Comment by jpata** [comment]
Right. monitorProcStat gave something like this at the end of the job

```
73012 10634136 Mon Nov 29 10:48:33 CET 2021 Now 5130968 Mon Nov 29 10:58:05 CET 2021
73013 10634136 Mon Nov 29 10:48:33 CET 2021 Now 5106472 Mon Nov 29 10:58:05 CET 2021
73014 10634136 Mon Nov 29 10:48:33 CET 2021 Now 0 Mon Nov 29 10:58:05 CET 2021
10634136
```

so in this case, the max is 10634136 bytes? I will need to look into how to launch the monitorProcStat with the correct PID from the jenkins profiling script.

**Comment by slava77** [comment]
I usually do 
```
cmsRun step.py >& step.log &
lastPID=$!
~/tools/monitorProcStat.sh ${lastPID} >& ${lastPID}.step1.mem
```

**Comment by jpata** [comment]
right, I guess this can be injected in the profiling shell script that's generated in jenkins https://github.com/cms-sw/cms-bot/blob/f006bff67c7c5ee7dd11e064f4873b32aec8118c/reco_profiling/profileRunner.py#L214

**Comment by jpata** [comment]
FYI, we can continue the CMS-facing discussion here: https://github.com/cms-sw/cmssw/issues/36282
