### ISSUE TITLE
12_3_0_pre6 profiles are ready

### ISSUE THREAD

**Issue by jpata** [jpata/cms-reco-profiling-web#48]
Hi,

The igprof jobs for 12_3_0_pre6 have completed, the outputs are in
```
/eos/cms/store/user/cmsbuild/profiling/data/CMSSW_12_3_0_pre6/slc7_amd64_gcc10/
```

@xoqhdgh1002 Dongyub (what's his github?) can you please try to update the web page using the new jenkins job now?

**Comment by yeopjjang** [comment]
OK we'll try to update the web page as soon as possible

**Comment by jpata** [comment]
Thanks @xoqhdgh1002 and @yeopjjang! The [website](http://cms-reco-profiling.web.cern.ch/cms-reco-profiling/) is updated, everything looks good so far. Great work!
Let's discuss next week how the experience was so far with "release-analyze-reco-profiling" jenkins and if there are any changes you would like to propose to the workflow.
