### ISSUE TITLE
links are mangled for workflows starting with 1

### ISSUE THREAD

**Issue by slava77** [jpata/cms-reco-profiling-web#5]
and example is clear from https://cms-reco-profiling.web.cern.ch/cms-reco-profiling/cgi-bin/igprof-navigator/releases/CMSSW_11_3_0_pre5/11834.21/step3/cpu_endjob

all links in the tree have the leading `/1` -> `` problem
https://cms-reco-profiling.web.cern.ch/cms-reco-profiling/cgi-bin/igprof-navigator/releases/CMSSW_11_3_0_pre51834.21/step3/cpu_endjob/self
should be `CMSSW_11_3_0_pre5/11834.21/`

**Comment by slava77** [comment]
the issue is apparently only on the first page; deeper links are OK
e.g. from https://cms-reco-profiling.web.cern.ch/cms-reco-profiling/cgi-bin/igprof-navigator/releases/CMSSW_11_3_0_pre5/11834.21/step3/cpu_endjob/19

**Comment by jpata** [comment]
Thanks for pointing out, I fixed it in https://github.com/jpata/cms-reco-profiling-web/pull/6
