### ISSUE TITLE
Summary plot x-axis labels

### ISSUE THREAD

**Issue by jpata** [jpata/cms-reco-profiling-web#63]
Here http://cms-reco-profiling.web.cern.ch/cms-reco-profiling/results/summary_plot_html/CMSSW_12_4_step3_136.889.html
the x-axis of the summary plot is in event IDs, which is rather strange to read, as they are in the millions.

<img width="423" alt="Screenshot 2022-06-02 at 17 11 28" src="https://user-images.githubusercontent.com/69717/171648991-77f47879-1cc2-48dc-a0ab-460d3f309b7a.png">

It would be better to relabel the x-axis so it goes from 0 to the number of processed events, i.e. 0-5000.
It was also pointed out here by other CMS folks: https://github.com/cms-sw/cmssw/issues/38198#issuecomment-1144908481

@xoqhdgh1002 could you please take a look at it?

**Comment by xoqhdgh1002** [comment]
Sure, I will do that.
It will be more looking nice.

**Comment by xoqhdgh1002** [comment]
![image](https://user-images.githubusercontent.com/36912292/172544581-b9b4b18e-be7a-489f-80f4-b4dc55379c8e.png)
I relabeled the x-axis which is the number of processed events.
Please check and comments!
Thank you!

**Comment by jpata** [comment]
Thanks Bongho - this is great!
