### ISSUE TITLE
copy-paste errors for pre4 and pre5 TimeDiff

### ISSUE THREAD

**Issue by jpata** [jpata/cms-reco-profiling-web#9]
@xoqhdgh1002 I merged #8.

However, we noticed that for pre4 and pre5, there are some copy-paste errors:

 [TimeDiff]preview:81.8939 s/ev ==> 75.8557 s/ev 

is repeated several times for pre4 (step3, step4) and pre5 (step3, step4).

Can you check, and open a new PR to update the index.html?

**Comment by xoqhdgh1002** [comment]
The problem was fixed!
